import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Full-Stack Authentication",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} text-black`}>
				{/* Navbar */}
				<nav className="bg-gray-800 text-white p-4">
					<div className="container mx-auto flex justify-between items-center">
						<div className="text-2xl font-bold">Your Logo</div>
						<div className="flex space-x-4">
							<Link href="/login" className="hover:text-gray-300">
								Login
							</Link>
							<Link
								href="/signup"
								className="hover:text-gray-300"
							>
								Signup
							</Link>
						</div>
					</div>
				</nav>

				{children}

				{/* Footer */}
				<footer className="bg-gray-800 text-white text-center py-4">
					<p>&copy; 2024 Your Website. All rights reserved.</p>
				</footer>
				<Toaster />
			</body>
		</html>
	);
}
