"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import { NextUIProvider } from "@nextui-org/react";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Full-Stack Authentication",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} text-black flex flex-col h-screen`}
			>
				{/* <Providers> */}
				<Navbar />
				<main className="flex-1 overflow-y-auto">{children}</main>
				{/* Footer */}
				<footer className="bg-gray-800 text-white text-center py-4">
					<p>&copy; 2024 Your Website. All rights reserved.</p>
				</footer>
				{/* </Providers> */}
				<Toaster />
			</body>
		</html>
	);
}
