/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xb2V7N21ygD
 */
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";
import { Divider } from "@nextui-org/react";
import { JSX, SVGProps } from "react";

export function InvestmentsPage() {
	return (
		<div className="w-full py-6">
			<div className="container space-y-6 px-4 md:px-6">
				<div className="space-y-2">
					<h1 className="text-2xl font-bold tracking-tighter sm:text-2xl">
						My Investments
					</h1>
					<p className="max-w-[700px] text-gray-500 md:text-lg/relaxed dark:text-gray-400">
						Track and manage your investments in one place. Add
						stocks, real estate, and other assets to monitor their
						performance and value over time.
					</p>
				</div>
				<Divider />
				<div className="flex flex-col gap-4 min-[400px]:grid md:grid-cols-2 lg:grid-cols-3">
					<div className="flex flex-col gap-2">
						<div className="flex items-start gap-4">
							<div className="flex flex-col gap-1">
								<h2 className="text-xl font-semibold">
									Stocks
								</h2>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Monitor all of your stock portfolio.
								</p>
							</div>
							<Button size="sm">Add</Button>
						</div>
						<Card>
							<CardContent className="flex items-center gap-4">
								<StoreIcon className="h-8 w-8" />
								<div className="flex-1 grid gap-1">
									<h3 className="font-semibold">AAPL</h3>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										Apple Inc. designs, markets smartphones,
									</p>
								</div>
								<div className="flex flex-col items-end">
									<p className="font-semibold">$135.47</p>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										+0.32 (0.24%)
									</p>
								</div>
							</CardContent>
						</Card>
						<Card>
							<CardContent className="flex items-center gap-4">
								<StoreIcon className="h-8 w-8" />
								<div className="flex-1 grid gap-1">
									<h3 className="font-semibold">TSLA</h3>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										Tesla, Inc. manufactures, and sells EV
									</p>
								</div>
								<div className="flex flex-col items-end">
									<p className="font-semibold">$950.00</p>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										+12.75 (1.36%)
									</p>
								</div>
							</CardContent>
						</Card>
					</div>
					<div className="flex flex-col gap-2">
						<div className="flex items-start gap-4">
							<div className="flex flex-col gap-1">
								<h2 className="text-xl font-semibold">
									Real Estate
								</h2>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Track the value of your real estate
									investments.
								</p>
							</div>
							<Button size="sm">Add</Button>
						</div>
						<Card>
							<CardContent className="flex items-center gap-4">
								<HomeIcon className="h-8 w-8" />
								<div className="flex-1 grid gap-1">
									<h3 className="font-semibold">
										123 Main St
									</h3>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										Charming 3-bedroom, 2-bath home in a
										quiet neighborhood.
									</p>
								</div>
								<div className="flex flex-col items-end">
									<p className="font-semibold">$350,000</p>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										+12.75 (1.36%)
									</p>
								</div>
							</CardContent>
						</Card>
					</div>
					<div className="flex flex-col gap-2">
						<div className="flex items-start gap-4">
							<div className="flex flex-col gap-1">
								<h2 className="text-xl font-semibold">Other</h2>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Add other investments to track their
									performance.
								</p>
							</div>
							<Button size="sm">Add</Button>
						</div>
						<Card>
							<CardContent className="flex items-center gap-4">
								<DollarSignIcon className="h-8 w-8" />
								<div className="flex-1 grid gap-1">
									<h3 className="font-semibold">Savings</h3>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										High-yield savings account for rainy
										days and future adventures.
									</p>
								</div>
								<div className="flex flex-col items-end">
									<p className="font-semibold">$10,000</p>
									<p className="text-sm text-gray-500 dark:text-gray-400">
										+200.00 (2.00%)
									</p>
								</div>
							</CardContent>
						</Card>
					</div>
				</div>
			</div>
		</div>
	);
}

function StoreIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7" />
			<path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
			<path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
			<path d="M2 7h20" />
			<path d="M22 7v3a2 2 0 0 1-2 2v0a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12v0a2 2 0 0 1-2-2V7" />
		</svg>
	);
}

function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
			<polyline points="9 22 9 12 15 12 15 22" />
		</svg>
	);
}

function DollarSignIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<line x1="12" x2="12" y1="2" y2="22" />
			<path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
		</svg>
	);
}
