/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LqFXnx2mzCT
 */
import {
	CardTitle,
	CardDescription,
	CardHeader,
	CardContent,
	Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
	TableHead,
	TableRow,
	TableHeader,
	TableCell,
	TableBody,
	Table,
} from "@/components/ui/table";
import Link from "next/link";
import { JSX, SVGProps } from "react";

export function RecentTransaction() {
	return (
		<Card className="w-full max-w-5xl">
			<CardHeader>
				<CardTitle>Recent transactions</CardTitle>
				<CardDescription>
					View your recent transactions.
				</CardDescription>
			</CardHeader>
			<CardContent>
				<div className="flex items-center gap-4 mb-4">
					<Button className="h-8 w-8" size="icon" variant="outline">
						<ChevronLeftIcon className="h-4 w-4" />
						<span className="sr-only">Previous</span>
					</Button>
					<div className="flex-1 text-sm text-gray-500 dark:text-gray-400">
						Showing 1 to 10 of 200 transactions
					</div>
					<Button className="h-8 w-8" size="icon" variant="outline">
						<ChevronRightIcon className="h-4 w-4" />
						<span className="sr-only">Next</span>
					</Button>
				</div>
				<Table>
					<TableHeader>
						<TableRow>
							<TableHead>Transaction ID</TableHead>
							<TableHead>Date</TableHead>
							<TableHead>Sender</TableHead>
							<TableHead>Receiver</TableHead>
							<TableHead>Method</TableHead>
							<TableHead>Amount</TableHead>
						</TableRow>
					</TableHeader>
					<TableBody>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12345
								</Link>
							</TableCell>
							<TableCell>2023-06-12</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>John Doe</TableCell>
							<TableCell>Credit card</TableCell>
							<TableCell>$250.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12346
								</Link>
							</TableCell>
							<TableCell>2023-06-13</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Jane Smith</TableCell>
							<TableCell>Bank transfer</TableCell>
							<TableCell>$150.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12347
								</Link>
							</TableCell>
							<TableCell>2023-06-14</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Bob Johnson</TableCell>
							<TableCell>Debit card</TableCell>
							<TableCell>$100.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12348
								</Link>
							</TableCell>
							<TableCell>2023-06-15</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Emily White</TableCell>
							<TableCell>PayPal</TableCell>
							<TableCell>$75.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12349
								</Link>
							</TableCell>
							<TableCell>2023-06-16</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Mike Brown</TableCell>
							<TableCell>Bitcoin</TableCell>
							<TableCell>$300.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12350
								</Link>
							</TableCell>
							<TableCell>2023-06-17</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Lisa Green</TableCell>
							<TableCell>Ethereum</TableCell>
							<TableCell>$200.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12351
								</Link>
							</TableCell>
							<TableCell>2023-06-18</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Chris Black</TableCell>
							<TableCell>Litecoin</TableCell>
							<TableCell>$125.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12352
								</Link>
							</TableCell>
							<TableCell>2023-06-19</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Olivia Red</TableCell>
							<TableCell>Ripple</TableCell>
							<TableCell>$50.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12353
								</Link>
							</TableCell>
							<TableCell>2023-06-20</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>William Yellow</TableCell>
							<TableCell>Visa</TableCell>
							<TableCell>$175.00</TableCell>
						</TableRow>
						<TableRow>
							<TableCell>
								<Link className="underline" href="#">
									#12354
								</Link>
							</TableCell>
							<TableCell>2023-06-21</TableCell>
							<TableCell>Acme Inc</TableCell>
							<TableCell>Sophia Blue</TableCell>
							<TableCell>Mastercard</TableCell>
							<TableCell>$225.00</TableCell>
						</TableRow>
					</TableBody>
				</Table>
			</CardContent>
		</Card>
	);
}

function ChevronLeftIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m15 18-6-6 6-6" />
		</svg>
	);
}

function ChevronRightIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m9 18 6-6-6-6" />
		</svg>
	);
}
